markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]

name: Shaharia Azam
url: http://v2.shahariaazam.com
description: Personal website of Shaharia Azam
twitter: shaharia
github: shahariaazam
#gravatar_url: nil